version: '3.6'

services:
  client:
    build: ./
    container_name: client
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    working_dir: /usr/src/app
    command: npm run start
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development